### ISSUE TITLE
disable default configuration

### ISSUE THREAD

**Issue by raedatoui** [rentzsch/nginx-homebrew-support#2]
i cloned your repo and followed instructions but nginx is still using the default config files located in /usr/local/etc/nginx/.
Isnt this supposed to override the default nginx structure?

**Comment by rentzsch** [comment]
It should, I think. However if you already issued the recipe's suggested `launchctl` loading of its homebrew.mxcl.nginx.plist, then you'll need to back it out yourself too.

It would be cool if install.rb detected this situation and offered to remove the offending previous launchctl item. Patches welcome.
